# -*- coding: utf-8 -*-
"""soal_2_listspinner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ne1L-lwOp5XFqUDeD7wfyJ5K2vJ6lA3a
"""

def counterClockwise(numlist):
  '''
  Fungsi untuk memutar elemen list secara berlawanan jarum jam.
  Misalnya, dari:
  [[1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]]

  menjadi:
  [[3, 6, 9],
  [2, 5, 8],
  [1, 4, 7]]

  Pola perubahannya adalah seperti ini:
  
  POSISI AWAL       POSISI AKHIR
  i = 0
  #F                 #F
  [i][2] =>         [i][i] #3
  [i][1] =>         [j][i] #2
  [i][i] =>         [k][i] #1

  j = 1 
  #F                #F
  [j][2] =>         [i][j] #6
  [j][1] =>         [j][j] #5
  [j][0] =>         [k][j] #4

  k = 2
  #F                #F
  [k][2] =>         [i][k]
  [k][1] =>         [j][k]
  [k][0] =>         [k][k]

  KETERANGAN:
  i,j,k = iterasi dari 0,1,2
  #F merupakan keterangan bahwa angka tersebut FIXED mengikuti iterasi utama, bukan nested.

  CONTOH PENGHITUNGAN
  rotated = [[], [], []]

      # iterasi 0 --> rotated[0].append( numlist[0][0] )
      # iterasi 1 --> rotated[1].append( numlist[1][0] )
      # iterasi 2 --> rotated[2].append( numlist[2][0] )
      # dan seterusnya.

  '''

  rotated = [[], [], []]                                  # assign variable 'rotated' berisi empty list untuk pengumpulan data dalam proses iterasi
  n_list = len(numlist)                                   # assign variable 'n_list' berisikan jumlah data dalam input; assign variable untuk readibility
  
  for i in range(n_list):                                 # masuk ke iterasi utama FOR LOOP dari 0 hingga jumlah data dalam input (n_list)
    for j in range(n_list):                               # masuk ke NESTED FOR LOOP dari 0 hingga jumlah data dalam input (n_list)
      rotated[i].append( numlist[j][ (n_list-1)-i ] )     # Menggunakan indexing dengan angka dari NESTED LOOP dan FOR LOOP, angka-angka tersebut secara berurutan untuk indexing dari list input. Kemudian dimasukkan ke list baru  'rotated'. Dan seterusnya. Untuk penjelasan dan simulasi dapat dilihat di docstring.
  return rotated                                          # return 'rotated' list yang telah diiterasi.


ar = [[1, 2, 3],
[4, 5, 6],
[7, 8, 9]]

counterClockwise(ar)